security:
    password_hashers:
        App\Entity\DeliveryPerson:
            algorithm: auto

    providers:
        delivery_person_provider:
            entity:
                class: App\Entity\DeliveryPerson
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/products, roles: PUBLIC_ACCESS }
        - { path: ^/api/delivery-persons, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_DELIVERY_PERSON }